services:
  jibas_db:
    image: mariadb:11
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - "jibas_mysql_data:/var/lib/mysql"
      - ./config/mariadb/custom.cnf:/etc/mysql/conf.d/custom.cnf
    ports:
      - "${DB_PORT}:3306"
    networks:
      - jibas_network

volumes:
  jibas_mysql_data:

networks:
  jibas_network:
    driver: bridge
